### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Tealium/tealium-data-enrichment-gtm-template#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values for creating the url. This method returns an encoded Uniform Resource Identifier (URI) by escaping special characters. You should use this method on data.endpoint, data.tealiumAccount, data.tealiumProfile when generating the url
url = data.endpoint + '/' + data.tealiumAccount + '/' + data.tealiumProfile + '/' +
        visitorId + '?callback=tealium_gtm_enrich&rnd=' + timestamp;

**Comment by tygavin** [comment]
Thank you for your review.  This is now updated. 👍
